name: DevSecOps Security Pipeline 

  

on: 

  push: 

    branches: [main] 

  pull_request: 

    branches: [main] 

  

jobs: 

  sca: 

    name: Software Composition Analysis 

    runs-on: ubuntu-latest 

  

    steps: 

      - name: Checkout repository 

        uses: actions/checkout@v4 

  

      - name: Set up Node.js 

        uses: actions/setup-node@v4 

        with: 

          node-version: 18 

  

      - name: Set up Python 

        uses: actions/setup-python@v5 

        with: 

          python-version: "3.11" 

  

      - name: Install Node dependencies 

        working-directory: api 

        run: npm install 

  

      - name: Run Snyk Open Source Scan 

        uses: snyk/actions/node@master 

        continue-on-error: true 

        env: 

          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 

        with: 

          args: --file=api/package.json 

  

  build-test: 

    name: Build and Test 

    runs-on: ubuntu-latest 

    needs: sca 

  

    steps: 

      - name: Checkout repository 

        uses: actions/checkout@v4 

  

      - name: Build Docker images 

        run: docker compose build 
